# This is a basic workflow to help you get started with Actions

name: Buld Repo To Coding
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - name: Setup Git Infomation
        run: |
          git config --global user.name 'Akimoto' 
          git config --global user.email 'jaxsonwang@foxmail.com'
      - name: Deploy To Coding Pages
        env:
          Coding_Project_Name: ${ secrets.PROJECT_NAME}
          Coding_Token: ${{ secrets.TOKEN_CODINGAPI }}
          Coding_Username: ${{ secrets.USERNAME_CODING }} 
          commit_message: ${{ github.event.head_commit.message }}
        run: | 

          rm CNAME
          rm -rf .github
          rm -rf .git
          git clone https://${Coding_Username}:${Coding_Token}@${Coding_Username}.coding.net/${Coding_Username}/${Coding_Project_Name}.git
          git clone git@e.coding.net:${Coding_Username}/${Coding_Project_Name}/${Coding_Project_Name}.git coding_dir
          cd coding_dir && mv .git ../ && cd ../ && rm -rf coding_dir
          git config --local user.email "jaxsonwang@foxmail.com"
          git config --local user.name "Akimoto"
          git config core.filemode false
          git remote set-url origin https://e.coding.net/${Coding_Username}/${Coding_Project_Name}/${Coding_Project_Name}.git
          git add .
          git commit -F ${commit_message}
          git push --force --quiet "https://${Coding_Username}:${Coding_Token}@${Coding_Username}.coding.net/${Coding_Username}/${Coding_Project_Name}.git" master:master

